use std::collections::HashSet;

use crate::aliases::SCHEMA_ALIASES;
use crate::crc::{crc32, make_crc_table};
use crate::model::{Entity, Schema, TypeDef};
use crate::Result;

pub fn generate_rust(schemas: &[Schema]) -> Result<String> {
    let crc_table = make_crc_table();
    let mut output = Vec::new();

    output.push("// This file is generated by src/rust/schema-generator".to_string());
    output.push("#![allow(non_camel_case_types, non_snake_case, dead_code)]".to_string());
    output.push("".to_string());
    output.push("use std::marker::PhantomData;".to_string());
    output.push("".to_string());
    output.push("#[derive(Clone, Debug, PartialEq)]".to_string());
    output.push("pub struct Handle<T> {".to_string());
    output.push("    pub value: i64,".to_string());
    output.push("    _marker: PhantomData<T>,".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("impl<T> Handle<T> {".to_string());
    output.push("    pub fn new(value: i64) -> Self {".to_string());
    output.push("        Self { value, _marker: PhantomData }".to_string());
    output.push("    }".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("#[derive(Clone, Debug, PartialEq)]".to_string());
    output.push("pub struct NumberHandle {".to_string());
    output.push("    pub value: f64,".to_string());
    output.push("    pub type_code: u32,".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("impl NumberHandle {".to_string());
    output.push("    pub fn new(value: f64, type_code: u32) -> Self {".to_string());
    output.push("        Self { value, type_code }".to_string());
    output.push("    }".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("#[allow(non_camel_case_types)]".to_string());
    output.push("#[derive(Copy, Clone, Debug, Eq, PartialEq)]".to_string());
    output.push("pub enum logical {".to_string());
    output.push("    FALSE,".to_string());
    output.push("    TRUE,".to_string());
    output.push("    UNKNOWN,".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("#[derive(Clone, Debug, Default, PartialEq)]".to_string());
    output.push("pub struct IfcLineObject {".to_string());
    output.push("    pub express_id: i64,".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("#[derive(Clone, Copy, Debug, PartialEq)]".to_string());
    output.push("pub struct PropertyDef {".to_string());
    output.push("    pub name: &'static str,".to_string());
    output.push("    pub type_code: u32,".to_string());
    output.push("}".to_string());
    output.push("".to_string());
    output.push("#[derive(Clone, Copy, Debug, PartialEq)]".to_string());
    output.push("pub struct EntityDef {".to_string());
    output.push("    pub type_code: u32,".to_string());
    output.push("    pub properties: &'static [PropertyDef],".to_string());
    output.push("}".to_string());
    output.push("".to_string());

    let mut all_names = OrderedSet::new();
    all_names.insert("FILE_SCHEMA".to_string());
    all_names.insert("FILE_NAME".to_string());
    all_names.insert("FILE_DESCRIPTION".to_string());

    let mut type_names = OrderedSet::new();
    let mut ifc_elements: HashSet<String> = HashSet::new();

    for schema in schemas {
        for entity in &schema.entities {
            all_names.insert(entity.name.clone());
            if entity.is_ifc_product {
                ifc_elements.insert(entity.name.clone());
            }
        }
        for ty in &schema.types {
            type_names.insert(ty.name.clone());
        }
    }

    for name in type_names.iter() {
        all_names.insert(name.clone());
    }

    output.push("// Schema CRC32 constants".to_string());
    for name in all_names.iter() {
        let upper = name.to_uppercase();
        let code = crc32(&upper, &crc_table);
        output.push(format!("pub const {upper}: u32 = {code}u32;"));
    }
    output.push("".to_string());

    output.push("#[derive(Copy, Clone, Debug, Eq, PartialEq)]".to_string());
    output.push("pub enum Schemas {".to_string());
    for schema in schemas {
        output.push(format!("    {},", schema.name_clean));
    }
    output.push("}".to_string());
    output.push("".to_string());

    output.push("pub static SCHEMA_NAMES: &[&[&str]] = &[".to_string());
    for schema in schemas {
        let mut names = vec![schema.name_clean.clone()];
        for alias in SCHEMA_ALIASES {
            if alias.alias == schema.name_clean {
                names.push(alias.schema_name.to_string());
            }
        }
        let joined = names
            .iter()
            .map(|name| format!("\"{name}\""))
            .collect::<Vec<_>>()
            .join(", ");
        output.push(format!("    &[{joined}],"));
    }
    output.push("];".to_string());
    output.push("".to_string());

    output.push("pub static IFC_ELEMENTS: &[u32] = &[".to_string());
    let mut elements: Vec<_> = ifc_elements.into_iter().collect();
    elements.sort();
    for element in elements {
        let upper = element.to_uppercase();
        output.push(format!("    {upper},"));
    }
    output.push("];".to_string());
    output.push("".to_string());

    for schema in schemas {
        output.extend(generate_schema_property_defs(schema, &crc_table));
    }

    output.extend(generate_property_helpers(schemas));

    for schema in schemas {
        output.push(format!("pub mod {} {{", schema.name_clean));
        output.push("    use super::{Handle, IfcLineObject, NumberHandle, logical};".to_string());
        output.push("".to_string());

        for ty in &schema.types {
            output.extend(generate_type(ty, &schema.types));
        }

        for entity in &schema.entities {
            output.extend(generate_entity(entity, &schema.types));
        }

        output.push("}".to_string());
        output.push("".to_string());
    }

    Ok(output.join("\n"))
}

fn generate_type(ty: &TypeDef, types: &[TypeDef]) -> Vec<String> {
    if ty.is_list {
        let inner = rust_type_from_name(&ty.type_name, types);
        return vec![
            "".to_string(),
            "    #[derive(Clone, Debug, PartialEq)]".to_string(),
            format!("    pub struct {}(pub Vec<{inner}>);", ty.name),
        ];
    }

    if ty.is_select {
        let mut lines = vec![
            "".to_string(),
            "    #[derive(Clone, Debug, PartialEq)]".to_string(),
            format!("    pub enum {} {{", ty.name),
        ];
        for value in &ty.values {
            let variant = sanitize_ident(value);
            let field_type = rust_type_from_name(value, types);
            lines.push(format!("        {variant}({field_type}),"));
        }
        lines.push("    }".to_string());
        return lines;
    }

    if ty.is_enum {
        let mut lines = vec![
            "".to_string(),
            "    #[derive(Copy, Clone, Debug, Eq, PartialEq)]".to_string(),
            format!("    pub enum {} {{", ty.name),
        ];
        for value in &ty.values {
            let variant = sanitize_ident(value);
            lines.push(format!("        {variant},"));
        }
        lines.push("    }".to_string());
        return lines;
    }

    let inner = rust_type_from_name(&ty.type_name, types);
    vec![
        "".to_string(),
        "    #[derive(Clone, Debug, PartialEq)]".to_string(),
        format!("    pub struct {}(pub {inner});", ty.name),
    ]
}

fn generate_entity(entity: &Entity, types: &[TypeDef]) -> Vec<String> {
    let mut lines = vec![
        "".to_string(),
        "    #[derive(Clone, Debug, PartialEq)]".to_string(),
        format!("    pub struct {} {{", entity.name),
        "        pub express_id: i64,".to_string(),
    ];

    for prop in entity
        .derived_props
        .iter()
        .filter(|prop| !entity.ifc_derived_props.contains(&prop.name))
    {
        let ty = rust_type_for_prop(prop, types);
        lines.push(format!("        pub {}: {},", prop.name, ty));
    }

    for prop in &entity.inverse_props {
        let mut ty = rust_type_from_name(&prop.type_name, types);
        if prop.set {
            ty = format!("Vec<{ty}>");
        }
        ty = format!("Option<{ty}>");
        lines.push(format!("        pub {}: {},", prop.name, ty));
    }

    lines.push("    }".to_string());
    lines
}

fn rust_type_for_prop(prop: &crate::model::Prop, types: &[TypeDef]) -> String {
    let mut ty = rust_type_from_name(&prop.type_name, types);
    if prop.set {
        let dimensions = if prop.dimensions == 0 {
            1
        } else {
            prop.dimensions
        };
        for _ in 0..dimensions {
            ty = format!("Vec<{ty}>");
        }
    }
    if prop.optional {
        ty = format!("Option<{ty}>");
    }
    ty
}

fn rust_type_from_name(type_name: &str, types: &[TypeDef]) -> String {
    match type_name {
        "number" => "NumberHandle".to_string(),
        "string" => "String".to_string(),
        "boolean" => "bool".to_string(),
        "logical" => "logical".to_string(),
        other => {
            if types.iter().any(|ty| ty.name == other) {
                other.to_string()
            } else {
                format!("Handle<{other}>")
            }
        }
    }
}

fn sanitize_ident(value: &str) -> String {
    let mut result = String::new();
    for ch in value.chars() {
        if ch.is_alphanumeric() || ch == '_' {
            result.push(ch);
        } else {
            result.push('_');
        }
    }
    if result
        .chars()
        .next()
        .map(|ch| ch.is_ascii_digit())
        .unwrap_or(false)
    {
        result.insert(0, '_');
    }
    if result.is_empty() {
        "_".to_string()
    } else {
        result
    }
}

fn generate_schema_property_defs(schema: &Schema, crc_table: &[u32; 256]) -> Vec<String> {
    let mut lines = Vec::new();
    lines.push(format!(
        "pub const {}_ENTITY_DEFS: &[EntityDef] = &[",
        schema.name_clean.to_uppercase()
    ));
    for entity in &schema.entities {
        let entity_code = crc32(&entity.name.to_uppercase(), crc_table);
        let props_name = format!(
            "{}_{}_PROPERTIES",
            schema.name_clean.to_uppercase(),
            entity.name.to_uppercase()
        );
        lines.push(format!(
            "    EntityDef {{ type_code: {entity_code}u32, properties: {props_name} }},"
        ));
    }
    lines.push("];".to_string());

    for entity in &schema.entities {
        let props_name = format!(
            "{}_{}_PROPERTIES",
            schema.name_clean.to_uppercase(),
            entity.name.to_uppercase()
        );
        lines.push(format!("pub const {props_name}: &[PropertyDef] = &["));
        for prop in entity
            .derived_props
            .iter()
            .filter(|prop| !entity.ifc_derived_props.contains(&prop.name))
        {
            let type_code = crc32(&prop.type_name.to_uppercase(), crc_table);
            lines.push(format!(
                "    PropertyDef {{ name: \"{}\", type_code: {}u32 }},",
                prop.name, type_code
            ));
        }
        lines.push("];".to_string());
    }
    lines.push("".to_string());
    lines
}

fn generate_property_helpers(schemas: &[Schema]) -> Vec<String> {
    let mut lines = Vec::new();
    lines.push("pub fn get_property_name(schema: Schemas, type_code: u32, prop: usize) -> Option<&'static str> {".to_string());
    lines.push(
        "    find_entity(schema, type_code)
        .and_then(|entity| entity.properties.get(prop))
        .map(|prop| prop.name)
}"
        .to_string(),
    );
    lines.push("".to_string());
    lines.push("pub fn get_property_type_code(schema: Schemas, type_code: u32, prop: usize) -> Option<u32> {".to_string());
    lines.push(
        "    find_entity(schema, type_code)
        .and_then(|entity| entity.properties.get(prop))
        .map(|prop| prop.type_code)
}"
        .to_string(),
    );
    lines.push("".to_string());
    lines.push(
        "pub fn get_property_count(schema: Schemas, type_code: u32) -> Option<usize> {".to_string(),
    );
    lines.push(
        "    find_entity(schema, type_code).map(|entity| entity.properties.len())".to_string(),
    );
    lines.push("}".to_string());
    lines.push("".to_string());
    lines.push(
        "fn find_entity(schema: Schemas, type_code: u32) -> Option<&'static EntityDef> {"
            .to_string(),
    );
    lines.push("    let defs = match schema {".to_string());
    for schema in schemas {
        let const_name = format!("{}_ENTITY_DEFS", schema.name_clean.to_uppercase());
        lines.push(format!(
            "        Schemas::{} => {const_name},",
            schema.name_clean
        ));
    }
    lines.push("    };".to_string());
    lines.push("    defs.iter().find(|def| def.type_code == type_code)".to_string());
    lines.push("}".to_string());
    lines.push("".to_string());
    lines
}

struct OrderedSet {
    items: Vec<String>,
    seen: HashSet<String>,
}

impl OrderedSet {
    fn new() -> Self {
        Self {
            items: Vec::new(),
            seen: HashSet::new(),
        }
    }

    fn insert(&mut self, value: String) {
        if self.seen.insert(value.clone()) {
            self.items.push(value);
        }
    }

    fn iter(&self) -> impl Iterator<Item = &String> {
        self.items.iter()
    }
}
